// <auto-generated />
namespace Press_Agency_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ConnectTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConnectTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060749332_ConnectTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
