// <auto-generated />
namespace Press_Agency_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class activeuserattribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(activeuserattribute));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051033021_activeuserattribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
